### ISSUE TITLE
no method matching VectorizationBase.Pointer{Float64}

### ISSUE THREAD

**Issue by magerton** [chriselrod/VectorizationBase.jl#1]
@chriselrod , thanks for the quick response on the PR just now.

I'm getting an error that (I think?) is coming from VectorizationBase.jl

```
Custom logsumexp functions: Error During Test at D:\libraries\julia\dev\ShaleDrillingLikelihood\test\utilities\sum-functions.jl:41
  Test threw exception
  Expression: bmark ≈ logsumexp!(z1, x)
  MethodError: no method matching VectorizationBase.Pointer{Float64}(::Ptr{Float64})
  Stacktrace:
   [1] macro expansion at D:\libraries\julia\packages\VectorizationBase\KoDSv\src\vectorizable.jl:305 [inlined]
   [2] vectorizable at D:\libraries\julia\packages\VectorizationBase\KoDSv\src\vectorizable.jl:297 [inlined]
   [3] macro expansion at .\gcutils.jl:189 [inlined]
   [4] macro expansion at D:\libraries\julia\packages\LoopVectorization\QozFw\src\LoopVectorization.jl:333 [inlined]
   [5] macro expansion at D:\libraries\julia\dev\ShaleDrillingLikelihood\src\utilities\sum-functions.jl:94 [inlined]
   [6] logsumexp!(::Array{Float64,1}, ::SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true}) at D:\libraries\julia\dev\ShaleDrillingLikelihood\src\utilities\sum-functions.jl:84
   [7] top-level scope at D:\libraries\julia\dev\ShaleDrillingLikelihood\test\utilities\sum-functions.jl:41
   [8] top-level scope at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Test\src\Test.jl:1113
   [9] top-level scope at D:\libraries\julia\dev\ShaleDrillingLikelihood\test\utilities\sum-functions.jl:33

Custom logsumexp functions: Error During Test at D:\libraries\julia\dev\ShaleDrillingLikelihood\test\utilities\sum-functions.jl:41
```
Original code is
```julia
"""
    logsumexp!(r, x)

Compute `r` = softmax(x) and return `logsumexp(x)`.

Based on code from
https://arxiv.org/pdf/1412.8695.pdf eq 3.8 for p(y)
https://discourse.julialang.org/t/fast-logsumexp/22827/7?u=baggepinnen for stable logsumexp
"""
@generated function logsumexp!(r::AbstractArray{T}, x::AbstractArray{T}) where {T}
    quote
        n = length(x)
        length(r) == n || throw(DimensionMismatch())
        isempty(x) && return -T(Inf)
        1 == stride1(r) == stride1(x) || throw(error("Arrays not strided"))

        u = maximum(x)                                       # max value used to re-center
        abs(u) == Inf && return any(isnan, x) ? T(NaN) : u   # check for non-finite values

        s = zero(T)
        @vectorize $T for i = 1:n
            tmp = exp(x[i] - u)
            r[i] = tmp
            s += tmp
        end

        invs = inv(s)
        r .*= invs

        return log1p(s-1) + u
    end
end
```

See screenshot

![image](https://user-images.githubusercontent.com/7339073/70840820-e4a6f380-1dc9-11ea-9e96-addfd81f9ab0.png)

**Comment by magerton** [comment]
Version info + pkgs are

```
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) W-2145 CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = D:\libraries\julia
  JULIA_NUM_THREADS = 8
  JULIA_PKGDIR = D:\libraries\julia
  JULIA_PKG_DEVDIR = D:\libraries\julia\dev

(v1.2) pkg> status
    Status `D:\libraries\julia\environments\v1.2\Project.toml`
  [c52e3926] Atom v0.11.3
  [8f4d0f93] Conda v1.3.0
  [fc19a607] CountPlus v0.0.0 #master (https://github.com/magerton/CountPlus)
  [0c46a032] DifferentialEquations v6.9.0
  [e61441de] GenGlobal v0.0.0 #master (https://github.com/magerton/GenGlobal.jl)
  [05a64641] Halton v0.0.1 #master (https://github.com/magerton/Halton)
  [7073ff75] IJulia v1.20.2
  [e5e0dc1b] Juno v0.7.2
  [bdcacae8] LoopVectorization v0.1.0 #master (https://github.com/chriselrod/LoopVectorization.jl)
  [76087f3c] NLopt v0.5.1
  [91a5bcdd] Plots v0.28.3
  [21efa798] SIMDPirates v0.1.0 #master (https://github.com/chriselrod/SIMDPirates.jl)
  [476501e8] SLEEFPirates v0.1.0 #master (https://github.com/chriselrod/SLEEFPirates.jl)
  [86eebf76] ShaleDrillingLikelihood v0.0.0 [`D:\libraries\julia\dev\ShaleDrillingLikelihood`]
  [3d5dd08c] VectorizationBase v0.1.0 #master (https://github.com/chriselrod/VectorizationBase.jl)
```

**Comment by magerton** [comment]
Reverting to https://github.com/chriselrod/SIMDPirates.jl/commit/11e458765d29291a59857d6884db071822b01652 and b2c1b05 fixed the problem

**Comment by chriselrod** [comment]
Sorry about this. I'm planning on registering these packages in the next month or so, which will make it easier to stay on working versions. 

For now, I added your `logsumexp!` function as [the first test for LoopVectorization](https://github.com/chriselrod/LoopVectorization.jl/blob/graphs/test/runtests.jl).
Thanks again for the commit. I'll try to start adding tests, and please feel free to submit any new issues/PRs/code for additional tests.

**Comment by magerton** [comment]
Thanks, @chriselrod! I appreciate your making your work public, and am glad to get to contribute a few lines. 😄 The faster, vectorized `logsumexp!` has been helpful in my research. 

I noticed the test is on the `graph` branch. To avoid breaking things, should I just stick with chriselrod/SIMDPirates.jl@11e4587 and b2c1b05 for now and wait until master gets updated?

**Comment by chriselrod** [comment]
Yes, if things work for now, it would certainly be safer to stay on those commits. But I'll try and keep master less volatile, and then ultimately start creating releases so that folks can easily just stay on the latest release.

I reduced the compile times in the graphs branch by replacing all the instances of `MacroTools.@capture` with code friendlier to the compiler. I suspect it can be improved much further, but this already took several seconds off of the testcase I was using.

I could "backport" these changes if it looks like it will take much longer for me to be able to merge in the branch.

The focus of that branch was to allow it to use nested loops, and perform optimizations to save on reloading values into registers. For example, it should be able to generate [decent gemv code](https://discourse.julialang.org/t/why-mul-is-so-fast/31436/6?u=elrod) for small matrices, however I'm not adding any cache-optimizations yet that will be important for larger arrays (note that llvm polly and gcc's graphite do cache, rather than register, optimizations).
This new functionality won't help special functions like `log`, because these functions eat up most of the CPU's registers, so none of the transformations are really profitable. I'll use a different macro for this to avoid breaking code.

**Comment by magerton** [comment]
Thanks -- I'll plan to stick to those commits for now. Those are some impressive speedups!

**Comment by chriselrod** [comment]
I've registered those 4 packages, but am now thinking I'll deprecate `@vectorize` in favor of `@avx` in an upcoming release.

**Comment by magerton** [comment]
Thanks, @chriselrod! I'll upgrade my code and swap in `@avx` for `@vectorize`.
