### ISSUE TITLE
A question regarding vmap!

### ISSUE THREAD

**Issue by nhavt** [chriselrod/VectorizationBase.jl#17]
Hi Chris,

I have a question regarding the use of vmap! I am wondering whether it is possible to use a function involving the ternary operator in vmap! Below is an example. Thanks very much in advance! 

`x = rand(10^4); 
y = rand(10^4); 
z = similar(x);
f(x,y) = x==y ? 2.0 : 0.0
vmap!(f, z, x, y);`

**Comment by chriselrod** [comment]
With the latest release of `LoopVectorization`, you should use `SIMDPirates.vifelse`.
There will be a breaking change fairly soon that switches this to `IfElse.ifelse`.

**Comment by nhavt** [comment]
Hi Chris, thanks very much for your quick response. So, I will then wait a bit.
